language: clojure
jdk:
  - oraclejdk8
sudo: true
before_install:
  - wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
  - tar -xjf phantomjs-2.0.0-ubuntu-12.04.tar.bz2
  - sudo rm -rf /usr/local/phantomjs/bin/phantomjs
  - sudo mv phantomjs /usr/local/phantomjs/bin/phantomjs
  - sudo bash -c "cd /usr/local/bin && curl -fsSLo boot https://github.com/boot-clj/boot-bin/releases/download/latest/boot.sh && chmod 755 boot"
install:
  - boot repl -e '(System/exit 0)'
before_script:
  - export BOOT_JVM_OPTIONS="-Xms256m -Xmx2048m"
  - echo $BOOT_JVM_OPTIONS
script:
  - boot test!
  # currently disabled because of https://github.com/tolitius/boot-check/issues/2
  # - boot check/with-kibit
cache:
  directories:
  - "$HOME/.m2"
branches:
  only:
  - master
  - mainline
notifications:
  slack:
    secure: ARbvDz3oduvMPxFD5IwSgcygyajJJUQ8Vu9saa8RWuHuFjERT8Kh0KC9diKgISHgBZyRmUkiL+2hO/ICMg6R+CpFmkKfzZXZbLXeAL2yi3/Pm4vRVohhQFBDtYE9eby/yxSmKXcuBRpPdBTNilw3q+MITBOqn1lBZIBPKF5NgCakIEq+RSvv8ImSqqw1qKpAJrzBQpS3mriVEQJQgof70G1sY6RvCgCV5rvxiKD/xJp+qdSaVcT/qpTN5FZ/0dy+wSKjwOUOlr6FtbAjglrX5WnpHV072HTNtYqqdGa7n8MzxxN8N93F2ehC9xQqvYDg6O/OJjCz46idKV+TsYpi01aX0KAkuEelAhwhKhL/2TBN78Qf0edyKBEJqQHbYok7zNsbDUTblCOWgKqED/mAbC8BsmVgjpRlDcxtyxIDu1j3Fo8qXVlMtckZVfqu+GCA3RlVenqHi/GenjyFTIqQjK/y9KwAMLkmXQQVHNv1praTI8x4nOSqYcdsH2yGaTSWnZME29mUMgdN4F7gZfXWAeg11w3kvWuagDTn53cpZbaHPDYp9cQ9JdMCW6DJuG28zC9hCJc5atlwgs0ljoDwqV9/CPQtmjfnq1nMyhEcYeSX20E0vTzHL370Y6qyz9jBCI1Iw7seG5ozcR5KKhDbrweXaXpGd5CsO70BYSwqwUw=